### ISSUE TITLE
Put Types into tuples and records instead of Raw Types

### ISSUE THREAD

**Issue by aj3189** [PrincetonUniversity/lucid#29]
Right now the type of a record/tuple includes a list of raw types, rather than a list of types. Is there a reason for this? The issue came up when trying to add information into the type but this information cannot be properly propagated during inference because of the raw_ty rather than ty in a record/tuple type. If there is a good reason for the raw_ty then I will find something else, but if not then we should change it.

**Comment by DKLoehr** [comment]
IIRC the primary reason is because we don't want to assign separate effects to the subordinate types; rather, that effect should be derived from the effect of the overall type. There are probably other reasons as well, since raw types are generally easier to work with. If you really wanted to attach additional information, you could make a record analogous to the ty, exp statement, etc. records, which could contain annotations like span, and simply not give it an effect field.
